# Generated by Django 2.2.28 on 2023-03-09 06:39

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('typeform_webhook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdefinition',
            name='choices',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
