# Generated by Django 2.2.28 on 2023-04-13 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firebase-push-notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usernotification',
            name='created',
        ),
    ]
